### ISSUE TITLE
Prometheus set up with port 9090 even when 9095 in all.yml

### ISSUE THREAD

**Issue by alfonsomthd** [red-hat-storage/cockpit-ceph-installer#25]
After a successful deploy, I found out that prometheus container was constantly
restarting due to port 9090 being used by Cockpit UI.
Although in ```/usr/share/ceph-ansible/group_vars/all.yml```
prometheus_port: 9095,
in ```/usr/share/ceph-ansible/roles/ceph-defaults/defaults/main.yml```
prometheus_port: 9090
and it seems to be that this file takes priority over ```all.yml```.

Additionally, in
```/etc/prometheus/prometheus.yml```

I found out that grafana port was also 9090:
```
   - job_name: 'grafana'
     static_configs:
       - targets: [xxxxx:9090]
```
Installed Packages

Name         : ceph-ansible
Version      : 4.0.0
Release      : 0.1.rc16.el8cp
Architecture : noarch
Size         : 945 k
Source       : ceph-ansible-4.0.0-0.1.rc16.el8cp.src.rpm
Repository   : @System
From repo    : rhceph-4-tools-for-rhel-8-rpms
Summary      : Ansible playbooks for Ceph
URL          : https://github.com/ceph/ceph-ansible

Name         : cockpit-ceph-installer
Version      : 0.9
Release      : 1.el8cp
Architecture : noarch
Size         : 2.9 M
Source       : cockpit-ceph-installer-0.9-1.el8cp.src.rpm
Repository   : @System
From repo    : rhceph-4-tools-for-rhel-8-rpms
Summary      : Cockpit plugin for Ceph cluster installation

**Comment by jmolmo** [comment]
What i have found is that in my local installation the modification to include the Prometheus port in "/usr/share/ceph-ansible/roles/ceph-defaults/defaults/main.yml" was not present.

I have seen that this modification was introduced in:
https://github.com/ceph/ceph-ansible/commit/87db5aa55c9f6014e454c23a00b83704defe5911

and is included in:
https://github.com/ceph/ceph-ansible/releases/tag/v4.0.0rc12


Cockpit ceph installer only modifies the "all.yml" file to change the port, so it seems that it will be needed to change also the port in "/usr/share/ceph-ansible/roles/ceph-defaults/defaults/main.yml"
or
to modify directly the default ports that we are using in Ceph Ansible.

@alfonsomthd can you add as part of the information the version of ceph-ansible that you are using in your servers?

**Comment by alfonsomthd** [comment]
> @alfonsomthd can you add as part of the information the version of ceph-ansible that you are using in your servers?

@jmolmo Done: updated PR description with that info.

**Comment by pcuzner** [comment]
@alfonsomthd @jmolmo Yes I noticed this too last week. Now that ceph defaults are applied to each role, they take precedence over all.yml. Just checking best place for the override.

**Comment by pcuzner** [comment]
all.yml host_vars and group_vars all fail to override the ceph_defaults. Will talk to the ceph-ansible folks

**Comment by pcuzner** [comment]
ceph-ansible on master and on stable-4 branch now defaults to 9092. So the code to 'nudge' the port on has now been removed. There was a problem with the structure of the ceph-ansible playbook which meant that if the inventory wasn't in the same directory as the playbook group_vars were being ignored. This has also been addressed by the ceph-ansible guys.
