### ISSUE TITLE
How to add new osds/mons or all components?

### ISSUE THREAD

**Issue by xolseg** [red-hat-storage/cockpit-ceph-installer#31]
Hi, I looked at the src, but did not find ways to add any new components to the cluster, will this feature be added or should not wait for this feature in the future?

**Comment by pcuzner** [comment]
The goal is to get the cluster operational, and then use dashboard features to add new components (i.e. grow) the cluster. The ceph mgr has the orchestrator component, so the idea is to link the orchestrator into the dashboard UI to handle things like adding mds, rgw, osds in a more interactive way.

**Comment by pcuzner** [comment]
closing as answered - please reopen if required.
