### ISSUE TITLE
Host not found (DNS issue?)  

### ISSUE THREAD

**Issue by skunkr** [red-hat-storage/cockpit-ceph-installer#60]
Hi,
I have the "ceph1vm"  name resolvable from within the machine with cockpit-ceph-installer module installed.

```
PING ceph1vm (10.10.6.111) 56(84) bytes of data.
64 bytes from ceph1vm (10.10.6.111): icmp_seq=1 ttl=64 time=0.335 ms
```
However, when I try to add hosts,  it gives me this status "NOT OK" with "Host not found (DNS issue?)  "  error.

Have I missed to configure something ?
Thank you !

Leo

**Comment by leodavidsec** [comment]
Hi guys,
Any thoughts on this ?
I am still confrunting it.
Thank you !

**Comment by lbac-redhat** [comment]
This might be because the ansible-runner-service container has an old copy of /etc/resolv.conf or /etc/hosts if you have changed them after having run the container.

If those have been changed, you should restart the container - either with podman or the helper script like so:

ansible-runner-service.sh -k    # This will kill the currently running container
ansible-runner-service.sh -s    # This will start a new container

**Comment by imoyao** [comment]
you can try add you hosts info to /etc/hosts like this:
```
[anaconda root@armnode1 utils]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.10.15.202 node1  # your hosts ip  and hostname here
10.10.15.203 node2
10.10.15.204 node3
……
```
it works for me.

**Comment by BeastlyPixels** [comment]
I am currently having the same issue. I have tried restarting the ansible runner service but it did not work. I am trying to add them to the hosts file but no dice. I am going to keep at it. Any other suggestions?

**Comment by BeastlyPixels** [comment]
Still no luck, any other suggestions?

**Comment by BeastlyPixels** [comment]
Is having a private DNS server a requirement to run this?

**Comment by BeastlyPixels** [comment]
Okay, I found the issue. For me it was having to add the localhost name by itself to /etc/hosts.

127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.x.x.x localhost localhost.localdomain

**Comment by pcuzner** [comment]
Glad that you resolved he issue,

FYI - the current code prevents localhost from being uses as a host name when defining the hosts to deploy to
