### ISSUE TITLE
Cannot add ceph octopus target version

### ISSUE THREAD

**Issue by BeastlyPixels** [red-hat-storage/cockpit-ceph-installer#62]
Hello, I have the plugin installed and running on CentOS 8.1. When I run the installer and go to select the target, the newest version of ceph is not available. I am looking to install ceph octopus (15) on my cluster. Is there an option to add this as a target? Thank you!

**Comment by imoyao** [comment]
maybe you can have a try on [Updated for Ceph Octopus · JinxCappa/cockpit-ceph-installer@54fef53](https://github.com/JinxCappa/cockpit-ceph-installer/commit/54fef53f8845d3548b06919c71cd2d02f796dcd2)

**Comment by BeastlyPixels** [comment]
I appreciate your response, would it be okay to just install it over my existing installation?

**Comment by imoyao** [comment]
> I appreciate your response, would it be okay to just install it over my existing installation?

Sorry,I haven't really tried this solution.It seems like that just add a selection to the checkbox.

**Comment by BeastlyPixels** [comment]
I did have to reinstall and then restart the cockpit.socket service. It worked, thank you for your help!
