### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by BeastlyPixels** [red-hat-storage/cockpit-ceph-installer#78]
Hello, what is the easiest way to update to a later version of this tool? Thank you!

**Comment by pcuzner** [comment]
That depends on how you installed it :)

The quick and dirty way is to refresh the folder that you have cockpit looking at with the contents of dist from this repo. Every time we update the dist should be receiving updates (although the last couple of PR's skipped this!)

I'll get a refresh of the dist done soon.

Alternatively, the repo provides a spec, so you can build an rpm and upgrade that way.
